server:
  port: 8088


xss:
  enabled: true
  #  Exclude links (separate multiple links with commas)
  excludes: /ui/*
  #  match links (separate multiple links with commas)
  urlPatterns: /api/*,/admin/*