server:
  port: 8088
spring:
  mvc:
    contentnegotiation:
      #favor-path-extension: true  # header accept
      favor-parameter: true   # url ?format=xml or format=json
      media-types:
        json: application/json